name: Update QX Rules

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

# 显式声明权限，确保可以推送代码
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/convert.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add qx_rule.list
          # 即使没有更新也不报错
          git commit -m "Update rules" || echo "No changes to commit"
          git push
