name: Batch Update QX Rules

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动同步
  workflow_dispatch:      # 支持手动点击运行

permissions:
  contents: write         # 允许写入仓库

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/convert.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 添加文件夹下所有转换后的文件
          git add QuantumultX/*
          
          # 只有在有变动时才提交
          git commit -m "Auto-update rules: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
